# download the theme toml file beforehand at .config/alacritty
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Inconsolata Nerd Font", style = "Regular" } 
bold = { family = "Inconsolata Nerd Font", style = "Bold" } 
italic = { family = "Inconsolata Nerd Font", style = "Italic" } 
bold_italic = { family = "Inconsolata Nerd Font", style = "Bold Italic" } 
size = 12

